@echo off
setlocal

:: 1. 安装依赖
pip install pyinstaller pillow tkinterdnd2

:: 2. 下载FFmpeg（如果不存在）
if not exist "ffmpeg" (
    echo Downloading FFmpeg...
    curl -L -o ffmpeg.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
    tar -xf ffmpeg.zip
    ren ffmpeg-master-latest-win64-gpl ffmpeg
    del ffmpeg.zip
)

:: 3. 构建可执行文件
pyinstaller --onefile --windowed ^
    --name "VideoMergerTool" ^
    --icon "video_icon.ico" ^
    --add-data "ffmpeg;ffmpeg" ^
    --add-data "%APPDATA%\Python\Python310\site-packages\tkinterdnd2;tkinterdnd2" ^
    video_merger.py

:: 4. 复制文件到发布目录
mkdir release 2>nul
copy dist\VideoMergerTool.exe release
xcopy /E /I ffmpeg release\ffmpeg
copy video_merger.py release

echo 构建完成！请查看 release 文件夹
endlocal
