name: Build Windows Executable

on:
  push:
    branches: [ main, master, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Download FFmpeg
      run: |
        New-Item -ItemType Directory -Force -Path "ffmpeg/bin"
        Invoke-WebRequest -Uri "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full-shared.7z" -OutFile "ffmpeg.7z"
        choco install 7zip -y
        & "C:\Program Files\7-Zip\7z.exe" x ffmpeg.7z -offmpeg_temp
        $ffmpegExe = Get-ChildItem -Path "ffmpeg_temp" -Recurse -Filter "ffmpeg.exe" | Select-Object -First 1
        Copy-Item $ffmpegExe.FullName -Destination "ffmpeg/bin/ffmpeg.exe"
        Remove-Item -Recurse -Force ffmpeg_temp
        Remove-Item ffmpeg.7z
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "VideoScreenshotTool" --add-data "ffmpeg;ffmpeg" ffmpeg.py
        
    - name: Create release package
      run: |
        New-Item -ItemType Directory -Force -Path "release"
        Copy-Item "dist/VideoScreenshotTool.exe" -Destination "release/"
        Copy-Item -Recurse "ffmpeg" -Destination "release/"
        & "C:\Program Files\7-Zip\7z.exe" a -t7z "VideoScreenshotTool_Windows.7z" "release/*"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoScreenshotTool-Windows
        path: VideoScreenshotTool_Windows.7z
        retention-days: 30
