name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # 指定 Node.js 版本

    - name: Install dependencies
      run: |
        npm install puppeteer
        npm install -g pkg  # 安装 pkg

    - name: Build EXE
      run: |
        pkg fy-translator.js --output fy-translator.exe  # 打包成 exe 文件

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: fy-translator-exe
        path: fy-translator.exe
