name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pillow pyautogui pywin32 ttkbootstrap

    - name: Build with PyInstaller
      shell: powershell
      run: |
        $ttkPath = (pip show ttkbootstrap | Select-String 'Location:').ToString().Split()[1]
        pyinstaller --onefile --windowed --name "Excel图片工具" `
          --add-data "$ttkPath\ttkbootstrap;ttkbootstrap/" `
          --clean `
          cv4.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExcelImageTool
        path: dist/
