name: Build Video Merger Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow tkinterdnd2

    - name: Add pyinstaller to PATH
      run: echo "$env:USERPROFILE\AppData\Roaming\Python\Python310\Scripts" >> $env:GITHUB_PATH

    - name: Download FFmpeg for Windows
      run: |
        $ffmpegUrl = "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip"
        Invoke-WebRequest -Uri $ffmpegUrl -OutFile ffmpeg.zip
        Expand-Archive ffmpeg.zip -DestinationPath .
        Rename-Item -Path "ffmpeg-master-latest-win64-gpl" -NewName "ffmpeg"
        Remove-Item ffmpeg.zip

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed `
          --name "VideoMergerTool" `
          --icon "video_icon.ico" `
          --add-data "ffmpeg;ffmpeg" `
          --add-data "$env:USERPROFILE\AppData\Roaming\Python\Python310\site-packages/tkinterdnd2;tkinterdnd2" `
          video_merger.py

    - name: Create release package
      run: |
        mkdir release
        copy dist\VideoMergerTool.exe release
        xcopy /E /I ffmpeg release\ffmpeg
        echo "视频合并工具 - 使用说明" > release\README.txt
        echo "1. 运行 VideoMergerTool.exe" >> release\README.txt
        echo "2. 将视频文件拖放到程序窗口中" >> release\README.txt
        echo "3. 程序会自动合并视频并保存到源文件夹" >> release\README.txt
        echo "4. 需要保持 ffmpeg 文件夹与程序在同一目录" >> release\README.txt
        echo "" >> release\README.txt
        echo "注意：首次运行时可能会稍慢，请耐心等待" >> release\README.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VideoMergerTool
        path: release
