name: Build Windows Executable

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pillow tkinterdnd2
        
    - name: Find tkinterdnd2 path
      id: find-tkinterdnd2
      run: |
        $tkdndPath = python -c "import os, tkinterdnd2; print(os.path.dirname(tkinterdnd2.__file__))"
        echo "tkinterdnd2_path=$tkdndPath" >> $env:GITHUB_OUTPUT

    - name: Build executable
      run: |
        pyinstaller --onefile --windowed `
          --name "ImageMergerTool" `
          --icon "app_icon.ico" `
          --add-data "${{ steps.find-tkinterdnd2.outputs.tkinterdnd2_path };tkinterdnd2" `
          --hidden-import="PIL._tkinter_finder" `
          hb.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ImageMergerTool
        path: dist/ImageMergerTool.exe
