name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyqt5 pynput
        
    - name: Build executable
      shell: cmd
      run: |
        pyinstaller --onefile --windowed --name "FKeyAutoClicker" ^
          --icon "NONE" ^
          --add-data "%VIRTUAL_ENV%\Lib\site-packages\PyQt5\Qt5\plugins;PyQt5/Qt5/plugins" ^
          --add-data "%VIRTUAL_ENV%\Lib\site-packages\PyQt5\Qt5\bin;PyQt5/Qt5/bin" ^
          --hidden-import "pynput.keyboard._win32" ^
          --hidden-import "pynput.mouse._win32" ^
          --collect-all PyQt5 ^
          f.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FKeyAutoClicker
        path: dist/
