name: Build WebP Converter

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow tkinterdnd2 pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name webp2png webp_converter.py
        # 如果遇到模块找不到错误，添加：
        # --hidden-import tkinterdnd2

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webp2png-exe
        path: dist/webp2png.exe
