name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests Pillow numpy
        pip install pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile --hidden-import=win32clipboard --hidden-import=win32con --hidden-import=pyperclip db.py

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: db-exe
        path: dist/db.exe
